### ISSUE TITLE
provide code <-> ast functionality (lively.code)

### ISSUE THREAD

**Issue by JensLincke** [LivelyKernel/lively4-core#138]
<no description>

**Comment by JensLincke** [comment]
I think we are on it with /src/components/widgets/lively-code-mirror-ast-capabilities.js ?  @onsetsu am I right?

**Comment by onsetsu** [comment]
I believe this meant to improve the conversion between ast and code as a string.
We have that now with `'my.code'.traverseAsAST([...])` and others.
