### ISSUE TITLE
still no es6 in component load-script

### ISSUE THREAD

**Issue by Lixissimus** [LivelyKernel/lively4-core#16]
Although we can now use es6 in the templates, there is still no es6 in the script at the end of the template files, that is responsible for loading the component.

in `templates/lively-object-editor.html`, when I change
```
var ObjectEditor = modules[0];
var Loader = modules[1];
```
to
```
var [ObjectEditor, Loader] = modules;
```
it throws an error like `unexpected [`.

**Comment by onsetsu** [comment]
This needs some help of the service worker to parse .html files for es6 scripts.

For now, you can use the `spread` of the bluebird promise library. Bluebird is already included under `src/external/bluebird.js`:

```javascript
Promise.all([
  System.import('../templates/classes/ObjectEditor.js'),
  System.import('../src/client/morphic/component-loader.js')
]).spread((ObjectEditor, Loader) => {
  Loader.register('lively-object-editor', clone, Object.create(ObjectEditor.prototype || ObjectEditor.default.prototype));
});
```
or even:

```javascript
Promise.resolve([
  '../templates/classes/ObjectEditor.js',
  '../src/client/morphic/component-loader.js'
])
  .map(System.import)
  .spread((ObjectEditor, Loader) => {
    Loader.register('lively-object-editor', clone, Object.create(ObjectEditor.prototype || ObjectEditor.default.prototype));
  });
```

**Comment by JensLincke** [comment]
fixed and not needed any more
