### ISSUE TITLE
Offline First

### ISSUE THREAD

**Issue by JensLincke** [LivelyKernel/lively4-core#178]

**Comment by onsetsu** [comment]
We already have caching support in the service worker.

Stage 1 Experiment: Load Lively without internet
Expected: It should load.

Stage 2 Experiment: Edit a file without internet
Expected:
- Content should not be lost.
- When reloading the page still offline, the changed content file should be used.

Stage 3 Experiment: When internet is great again, what should happen?
Expected:
- When without a conflict: the change should be pushe to the server
- With conflict: Three-way Merge should be automatically applied
  - could potentially be harmful

Idea:
- Every offline session is a branch, that has to be explicitly merged
- Alternative: Allow to go back in time and branch later

**Comment by onsetsu** [comment]
blocked by #231

**Comment by JensLincke** [comment]
since we rely a lot of lively4-server for source control I think this base become more problematic now. I don't see that we have the need and manpower to strive for this feature any longer.
