### ISSUE TITLE
Disable backspace navigation

### ISSUE THREAD

**Issue by JensLincke** [LivelyKernel/lively4-core#20]
I accidentally hit "backspace" without keyboard focus and lost my page.

**Comment by Lixissimus** [comment]
```
document.body.addEventListener("keydown", (evt) => {
  if (evt.keyCode == 8) { // backspace
    evt.preventDefault();
  }
});
```
should do it. But maybe an alert like in lively <4 would be better? For me, it feels bad to disable widely known shortcuts. Also the alert would stop you from accidentally closing the tab or window.

**Comment by JensLincke** [comment]
Where should we put it.... I put it in the boostrap?

**Comment by Lixissimus** [comment]
Yes, maybe in load.js

**Comment by Lixissimus** [comment]
turns out, the code I posted above seems to block backspace also in input fields...

**Comment by JensLincke** [comment]
thanks, that is much cleaner... I think, we had the same code in Lively3 and I forgot about it.
