### ISSUE TITLE
Web component hook before livelyMigrate

### ISSUE THREAD

**Issue by onsetsu** [LivelyKernel/lively4-core#246]
When migrating WebComponent instances, `livelyMigrate` is executed *before* the `initialize` of the new component. This makes setup for migrated and new instances more difficult.

Is there a hook that executes before `livelyMigrate`.

**Comment by JensLincke** [comment]
should it execute after the initialize? livelyMigrate is the hook that comes before the initialize.

**Comment by JensLincke** [comment]
livelyPreMigrate allows elements do something in their working state before they get replaced
