### ISSUE TITLE
Make mounting of ServiceWorker mount points persistent

### ISSUE THREAD

**Issue by JensLincke** [LivelyKernel/lively4-core#25]

**Comment by JensLincke** [comment]
@jgraichen, we have used src/external/focalStorage.js to store the token in the browser. 
Could we do it to store the mount points when changed and replay them on startup?

focalStorage.setItem("githubToken", localStorage.GithubToken).then(function() {
		var cb = onAuthenticatedCallbacks[state]
		if (cb) {
			console.log("running onAuthenticated callback: " + cb)
			cb(token)
		} else {
			console.log("no callback found for" + state)
		}
	})

**Comment by jgraichen** [comment]
I'm working on that.

**Comment by JensLincke** [comment]
implemented

**Comment by jgraichen** [comment]
Cool, can you point me to a commit or file? Would love to see the implementation.

**Comment by JensLincke** [comment]
https://github.com/LivelyKernel/lively4-core/blob/gh-pages/src/swx/filesystem.jsx

```
    persistMounts() {
      var mounts = this.mountsAsJso()
      console.log("persist mounts: " + mounts)
      focalStorage.setItem("lively4mounts", mounts)
    }

    // #TODO refactor to "async/await style"
    loadMounts(){
      focalStorage.getItem("lively4mounts").then((mounts) => {
        try {
          mounts.forEach(mount => {
            console.log("mount ", mount)
            System.import('src/swx/fs/' + mount.name + '.jsx').then(fs => {
              this.mount(mount.path, fs.default, mount.options)
            })
          })
        } catch(e) {
          console.log("error loading mounts: " + e)
        }
      })
    }
```
