### ISSUE TITLE
Transaction Inactive Error

### ISSUE THREAD

**Issue by adius** [LivelyKernel/lively4-core#263]
https://lively-kernel.org/lively4/lively4-core/start.html currently yields 

```
load Lively4 failed:TransactionInactiveError: A request was placed against a transaction which is currently not active, or which is finished.
```

**Comment by adius** [comment]
This only occurs in FireFox. Maybe this warning is related:

```
TypeError: navigator.webkitPersistentStorage is undefined
```

**Comment by onsetsu** [comment]
As discussed, we currently do not support Firefow, and do not plan to do so in the foreseeable future.
