### ISSUE TITLE
Switching between template source code and view code via shortcuts

### ISSUE THREAD

**Issue by Thulur** [LivelyKernel/lively4-core#275]
As a programmer when editing the html file of a template I want to switch to the js file via a shortcut. The other way around should work too.

For example a second editor could be lauchned to display the second file and every following toggle will switch between the two opened editors.

As reference Visual Studio on default settings allows to switch between view and code via "F7" and "Shift + F7"

**Comment by Thulur** [comment]
@onsetsu @JensLincke, already talked with Stefan about it earlier

**Comment by onsetsu** [comment]
@Thulur You can now switch between a template's html and js source by pressing F7.

You can adjust the logic in *src/components/tools/lively-container.js* method `switchBetweenJSAndHTML` to your liking :)
