### ISSUE TITLE
Prevent request modification

### ISSUE THREAD

**Issue by NHoff95** [LivelyKernel/lively4-core#278]
Please implement an exceptional rule for the service worker to not modify requests to 'https://lively-kernel.org/lively4handwriting'.

**Comment by NHoff95** [comment]
I think I found a solution how to do that (see [/lively4-handwriting/src/external/lively4-serviceworker/src/swx.js](https://lively-kernel.org/lively4/lively4-handwriting/start.html?load=https://lively-kernel.org/lively4/lively4-handwriting/src/external/lively4-serviceworker/src/swx.js))

Is this the way how to do that?
`if (url.pathname.match(/lively4handwriting/)) return;`

**Comment by davidrauch** [comment]
Yes, that should bypass all Request rewriting and caching

**Comment by NHoff95** [comment]
OK, thank you. Then there is nothing more to do 😃
