### ISSUE TITLE
Upgrade to latest version of webcomponents

### ISSUE THREAD

**Issue by adius** [LivelyKernel/lively4-core#292]
The one you are using is deprecated 
(as seen on https://developer.mozilla.org/en-US/docs/Web/API/Element/createShadowRoot)

**Comment by JensLincke** [comment]
I trie to replace it, but it did not work as expected... So we wait a bit.

"But, new API hasn't been standardized and none of the browsers currently support it. So I would suggest to stick to createShadowRootfor now." https://stackoverflow.com/questions/34452028/atachshadow-vs-createshadowroot

**Comment by adius** [comment]
That answer you posted is 2 years old 😉

By now Chrome fully supports it: https://caniuse.com/#feat=shadowdomv1

Maybe there was another reason why it didn't work for you?

**Comment by JensLincke** [comment]
we have upgraded now
