### ISSUE TITLE
Close button for window list in context menu

### ISSUE THREAD

**Issue by onsetsu** [LivelyKernel/lively4-core#295]
Currently, our context menu shows a list of all open windows, but is only able to navigate to them by clicking.

I would like to close some windows directly from the context menu.

**Comment by JensLincke** [comment]
would it be ok, to use sub-menus for choosing the action, or would you prefere as special "X" right there?

For the latter we would require more powerful context menus.

**Comment by onsetsu** [comment]
Hm, the latter option would be preferrable, as the main use case is to close a bunch of windows fast and without too many user interactions.

**Comment by JensLincke** [comment]
was implemented
![image](https://user-images.githubusercontent.com/1466247/64688063-e344f280-d48b-11e9-819d-ce9a8b1b6181.png)
