### ISSUE TITLE
cat and ls in Terminal

### ISSUE THREAD

**Issue by JensLincke** [LivelyKernel/lively4-core#30]
Error: Executable not found: ls
   Error: Executable not found: cat

Should this work? @jgraichen

**Comment by jgraichen** [comment]
Yes.

They are loaded from `https://lively4/bin/<exec>.js`. What does the Chrome Console say?

**Comment by jgraichen** [comment]
Hmm, the lookup is broken on `github.io`. Sec...

**Comment by jgraichen** [comment]
Should be fixed now.

The client side `System.import("/bin/cat.js")` tried to load from current domain `github.io/bin/cat.js`. Now it uses `System.import("https://lively4/bin/cat.js")` and uses the actual file backend. Note that this uses the github API now and is suspect to rate limiting.

**Comment by jgraichen** [comment]
Please also note that the terminal is *not* an `<input>` tag or similar but a char buffer based VT100 emulator. The `sh.js` implementation is controlling the terminal using VT100 escape sequences (e.g. `"\x1b[24h"`) and manually echoing input (like libreadline). That may not be explicitly stated in the presentation.

**Comment by JensLincke** [comment]
thanks, it works now.
