### ISSUE TITLE
Lively4 does not boot with serviceworker (if not installed)

### ISSUE THREAD

**Issue by Thulur** [LivelyKernel/lively4-core#303]
![image](https://user-images.githubusercontent.com/7317880/38626330-97a7989a-3dac-11e8-9662-f9972e8e7fa9.png)

Lively4 fails to parse the import statements.
My current system has no installed serviceworker and is running on Chrome Version  65.0.3325.181 (Offizieller Build) (64-Bit).
[Canary Version 67.0.3394.0 (Offizieller Build) canary (64-Bit) has the same problem]

With the parameter ?noserviceworker Lively4 is still working.

**Comment by onsetsu** [comment]
I tried to reproduce the issue on Chromewith same Version 65.0.3325.181 (Offizieller Build) (64-Bit).
Therefore, I created a fresh local folder, `/bar` in my case.

However, I was unable to reproduce the issue when using https://lively-kernel.org/lively4/bar/start.html.

What url did you work under?
Maybe its some inconsistencies because we updated the service worker at some point between semesters.

**Comment by onsetsu** [comment]
Interestingly, I had the same issue on my normal working branch `/foo`.
However, the error messages did not reappear after loading the page a second time.

**Comment by onsetsu** [comment]
I finally managed to get the described behavior.

It can be view under https://lively-kernel.org/lively4/blub/start.html.

@JensLincke any ideas?

**Comment by Thulur** [comment]
Sofar the problem occured on every up to date branch on my computer (also https://lively-kernel.org/lively4/bar/start.html).

In between I read multiple times that adding type="module" to the script tag solves the problem (c.f.: https://stackoverflow.com/questions/47632562/es6-module-import-giving-uncaught-syntaxerror-unexpected-identifier?rq=1)

Didnt have the time to try it sofar...

**Comment by onsetsu** [comment]
Turns out that `cache.put` actually tries to parse the JavaScript file to cache (possibly for some optimization purpose). Then, when approaching an unsupported ES feature (such as module syntax in web worker), an error is thrown.

We now catch that error, and the file  still seems to be cached.
