### ISSUE TITLE
Where to store scripts

### ISSUE THREAD

**Issue by onsetsu** [LivelyKernel/lively4-core#312]
Currently, scripts and steps are stored in a dedicated folder, making persistence easy.
However, for most temporary tools created using vivide, this simply creates the overhead of deleting those scripts manually before commiting.

Probably, scripts should be persisted with the view they configure.
Thus, scripts will be only temporary for exploratory usage, persisted on client side across page reload, and persisted in the repository for shared tools.

Will talk to @marceltaeumel and @codeZeilen on how the original vivide handles this.

**Comment by onsetsu** [comment]
We may use `this.setJSONAttribute()` for this.

**Comment by Thulur** [comment]
Closed by cf768e4598c25951a380a1be60c2ac19092a45d1
