### ISSUE TITLE
Remaining container on screen

### ISSUE THREAD

**Issue by yoshikiohshima** [LivelyKernel/lively4-core#318]
I got into a situation where a window/container is left on screen.  This seems to happen when my editor went halfway off screen toward top-left, thus the controls are off screen.  Then, I tried to remove it via the halo... But what I can select is the content of the window but not the window itself.  So I left with the blank window I cannot interact anymore.
<img width="750" alt="3" src="https://user-images.githubusercontent.com/197249/39442601-a6e5b594-4c66-11e8-913c-1315ec98559d.png">

**Comment by yoshikiohshima** [comment]
(And I want to get a fresh start that does not have this.  But where is it stored?

**Comment by JensLincke** [comment]
the fixed browser uses the "fixed" layout style of the browser. When you scroll and navigate it will move with you. This "fixed" position does not play well with halos.  So when it gets some offset... it will stay. Your can reset it through toggling it in the preference menu.
