### ISSUE TITLE
Create a new component

### ISSUE THREAD

**Issue by yoshikiohshima** [LivelyKernel/lively4-core#320]
For what I would like to make, I thought that I could copy src/components/tools/lively-terminal.html and .js to lively-ipython.html and .js, edit the class name in it and try... But I get an error:

<img width="663" alt="4" src="https://user-images.githubusercontent.com/197249/39444752-a2ad29f6-4c6d-11e8-95c3-8eacf712a30c.png">

It may be another naming convention violation.  If so, what is the expected name (and location) of those files?

**Comment by JensLincke** [comment]
To create a new component, please use the 'create component'.

We use a convention, that 

`data-class="LivelyTerminal"` will search for a `lively-terminal.js` in all template directories.

so for your `lively-ipython`  it should be `data-class="LivelyIpython"` and  `lively-ipython.js`.

I guess you wrote `data-class="LivelyIPython"` and the the convention would look for
`lively-i-python.js`.
