### ISSUE TITLE
Pressing "ctrl + s" in a presentation minifies the underlying code

### ISSUE THREAD

**Issue by Thulur** [LivelyKernel/lively4-core#329]
Opening a presentation in the file browser in the "view mode" and pressing ctrl + s minifies the underlying code. In more complex examples this completely breakes the code of the presentation.

The change is easily obserable by opening the same file in two file editors, switching one into "edit mode" change focus to the one in "view mode" and pressing ctrl + s.

One of my embedded components utilizes the save function, therefore I need to be able to press save in a presentation without destroying it.

**Comment by JensLincke** [comment]
sorry, thought that I had fixed that already...

**Comment by Thulur** [comment]
@JensLincke my  presentation (doc/RP2018/vivide-js/presentation/presentation-2018-05-15.md) still does it.

**Comment by JensLincke** [comment]
@Thulur I opened your presentation and pressed CTRL+S and "saving in presentation mode not supported yet" appeared as expected... Does it still occur?
