### ISSUE TITLE
PUT Request to http://lively4/* fails when service worker is not started

### ISSUE THREAD

**Issue by JensLincke** [LivelyKernel/lively4-core#33]
DOMException: Failed to execute 'respondWith' on 'FetchEvent': The fetch event has already been responded to.
    at Error (native)
    at ServiceWorker.fetch (https://lively-kernel.org/lively4-jens/src/swx/swx.jsx!transpiled:110:31)
    at Module.fetch (https://lively-kernel.org/lively4-jens/src/swx/swx.jsx!transpiled:38:27)
    at https://lively-kernel.org/lively4-jens/swx-loader.js:59:19

Since the first request will start it, a second request will succeed.

**Comment by JensLincke** [comment]
@jgraichen, any ideas why the request was already answered?

**Comment by jgraichen** [comment]
@JensLincke Same as for [#32](https://github.com/LivelyKernel/lively4-core/issues/32#issuecomment-180765817). `PUT` is also idempotent.

**Comment by jgraichen** [comment]
I have not yet found a way to force the browser to wait for the service worker and really do pass every request to it. It's still trying to optimized things.

**Comment by JensLincke** [comment]
Could I figure out in the answer, if the browser did answer me prematurely and do myself wait for the service worker? So distinguishing it from actual fails handed me down from the service worker?

**Comment by jgraichen** [comment]
The request should raise an error as the domain name usually cannot be resolved.
