### ISSUE TITLE
Editor does not know about Float32Array

### ISSUE THREAD

**Issue by yoshikiohshima** [LivelyKernel/lively4-core#335]
![float32](https://user-images.githubusercontent.com/197249/40940957-4777e22c-67fe-11e8-8473-fb702df2815e.png)

But then it compiles and runs fine.

**Comment by onsetsu** [comment]
closed by d7d2a83b5bc646e4ddf02b61ed5f47a89deea426

**Comment by yoshikiohshima** [comment]
It is not only about Float32Array but all typed arrays.  Other globals such as WebGLRenderingContext is known so there might be a better fix than adding this to the list of non-standard globals.

**Comment by onsetsu** [comment]
`WebGLRenderingContext` is an ES5 built-in. In contrast, `Float32Array` is an ES6 built-in.

For now, I enabled ES6 built-ins by default.

As I do not know what concrete globals you expect, could you please report back whether it is now your expected behavior?

**Comment by yoshikiohshima** [comment]
I think now it is working as expected.  Perhaps Map and Promise how can be removed from globals?

**Comment by onsetsu** [comment]
Good idea.

Done in e0282cd7bda45f495f8312e4079d7e0ba5467011.
