### ISSUE TITLE
Failing to save a page

### ISSUE THREAD

**Issue by yoshikiohshima** [LivelyKernel/lively4-core#341]
I started getting this error often (I updated my local installation today.)

<img width="717" alt="1" src="https://user-images.githubusercontent.com/197249/41879338-0e036f98-788e-11e8-97cd-20df63d4284b.png">

**Comment by JensLincke** [comment]
is this solved?

**Comment by yoshikiohshima** [comment]
This was when I tried to choose the save menu item in the world, so now this issue is obsolete, I think.
