### ISSUE TITLE
Editor does not resize when hiding the file list view

### ISSUE THREAD

**Issue by yoshikiohshima** [LivelyKernel/lively4-core#343]
I can collapse the list of files in the directory but clicking the middle divider, but quite often the editor fails to resize itself:

In this image, the width of the CodeMIrror stays the same even after the list was collapsed.

<img width="668" alt="3" src="https://user-images.githubusercontent.com/197249/41881971-2c1cda7a-789b-11e8-8a6e-34821aec962e.png">

**Comment by JensLincke** [comment]
I know, that we had this problem. Can you reproduce it in the latest version?
