### ISSUE TITLE
inspect and print it are not consistent

### ISSUE THREAD

**Issue by yoshikiohshima** [LivelyKernel/lively4-core#344]
I am not sure what is happening, but I have a workspace where a value is held in a variable called 'b'.

If I print it (by ctrl-p), it shows what is in there.  In this case, it is an instance of ipython-tensorview component.  But If I inspect it (ctrl-i) I get an empty inspector.

<img width="594" alt="1" src="https://user-images.githubusercontent.com/197249/41882997-f1d642c4-78a0-11e8-8e10-53d845e604cd.png">
<img width="452" alt="2" src="https://user-images.githubusercontent.com/197249/41883003-f4055670-78a0-11e8-929d-c6ef21484bc4.png">

**Comment by JensLincke** [comment]
I could not reproduce it, are there any log / error messages? The inspector does not seem to be opened properly?

**Comment by yoshikiohshima** [comment]
I still get this.  No error in the console.  In the picture, first I evaluated the first line "var x = ...", then clear the console, and then put the cursor on the next line and pressed Ctrl-i.  I get an inspector window that is blank.

<img width="898" alt="1" src="https://user-images.githubusercontent.com/197249/42042721-a74605e0-7aa9-11e8-8b34-3abd06351e91.png">

**Comment by yoshikiohshima** [comment]
Believe it or not, if I leave the tab for a half an hour or so untouched, and come back to it, it sometimes shows the correct result.

**Comment by JensLincke** [comment]
To replicate this I need an failing example to work on... 
else I could only say: works for me ;-)
![image](https://user-images.githubusercontent.com/1466247/64686256-aa574e80-d488-11e9-8ade-31f55637c492.png)
