### ISSUE TITLE
Drag real objects instead of VivideObjects

### ISSUE THREAD

**Issue by onsetsu** [LivelyKernel/lively4-core#347]
When dragging selected data from a `VivideView`, the drag hint only shows `a VivideObject` as preview.

Instead, we should show the data behind these VivideObjects.

This is probably part of the bigger issue that we currently transmit VivideObjects instead of the wrapped data to the next view.

**Comment by Thulur** [comment]
@onsetsu bcffa39c6e85845ee1a23ec9108e7c2d12924029 fixes the problem for now. Nevertheless, the solution can be improved, by changing what a widget returns as when selected data are requested.
