### ISSUE TITLE
Web Components should wait for their subcomponents to be fully initialized

### ISSUE THREAD

**Issue by onsetsu** [LivelyKernel/lively4-core#374]
Currently, race conditions may happen, as with the `Graph-Control` component.

The `Graph-Control` uses a `Knot-View` defined in its template:

```html
<template id="graph-control" >
[...]
<div><knot-input id="open-knot-view"></knot-input></div>
```

This subcomponent is accessed in its `initialize` method:

```javascript
export default class GraphControl extends Morph {
  async initialize() {
    [...]
    let input = this.get('#open-knot-view');
    input.setLabel('Open Knot');
    [...]
```

Problem: In some scenarios, the `initliaze` method is called, before the `Knot-View` is fully loaded and initialized, so, `setLabel` is not understood.

Potential fix: properly wait recursively for all components defined in the shadowroot and as children, before calling `initialize`.

**Comment by JensLincke** [comment]
I tried to reproduce it... but failed so far... 

Can we reproduce it somehow here?

https://lively-kernel.org/lively4/lively4-jens/templates/foo-comp.html
https://lively-kernel.org/lively4/lively4-jens/templates/foo-comp-sub.js


![image](https://user-images.githubusercontent.com/1466247/56904339-59792780-6a9e-11e9-9e82-7c3a050eaf24.png)

**Comment by JensLincke** [comment]
seem to work since it did not happen again
