### ISSUE TITLE
TreeView.js typo

### ISSUE THREAD

**Issue by Lixissimus** [LivelyKernel/lively4-core#39]
The treeview component doesn't load, e.g. when opening an an ObjectEditor on something here https://lively-kernel.org/lively4/lively4-core/draft/start.html?load=https://lively-kernel.org/lively4/Lively4.wiki/WebDev16.md
Looks like it tries to load TreeView.js, although the filename should be Treeview.js

**Comment by JensLincke** [comment]
thanks, fixed
