### ISSUE TITLE
Scripts should not be reevaluated when generating a print view for a markdown presentation

### ISSUE THREAD

**Issue by phoeinx** [LivelyKernel/lively4-core#392]
![image](https://user-images.githubusercontent.com/34538290/68403285-fd920880-017c-11ea-8ba1-59aa05223a78.png)
Getting this error message when trying to print BP2019RH1/doc/presentations/printtest.md 
prbly because it fails to access relative link "../../scratch/pong.js"
#presentation #markdown

**Comment by JensLincke** [comment]
fixed
