### ISSUE TITLE
Formatting error in presentation when using specific style content

### ISSUE THREAD

**Issue by leowe** [LivelyKernel/lively4-core#400]
When using style="transform: rotate(90deg);" in img tag, the images overlap with other elements (see image).

![image](https://user-images.githubusercontent.com/13684843/71087950-a6c91700-219d-11ea-9e87-a634fafea689.png)

Code for slide:
```
---

### Map of Somalia 2

<img src="pictures/20191216_144420.jpg" height="250" style="transform: rotate(90deg);"/>

#### Explanation 

- Piecharts are placed on every regional unit containing values the individuals that belong to this regional unit answered. The values are chosen with a filter / switch. 
- When clicking on a pie-chart the values can be filtered for this district. The filter can be changed in the toplayer or any sublayer.

---
```

When using the print option to save to pdf, some of the images vanish.

![image](https://user-images.githubusercontent.com/13684843/71088114-058e9080-219e-11ea-8c24-751b79b8b4ae.png)

Code for slide:
```
---

### Preparation

<img src="pictures/20191217_100230.jpg" width="400" style="transform: rotate(90deg)"/>
<img src="pictures/20191217_100343.jpg" height="350" />
<img src="pictures/20191217_104406.jpg" height="350" />

--- 
```

To reproduce: See [https://lively-kernel.org/lively4/lively4-bp2019/start.html?load=https://lively-kernel.org/lively4/BP2019RH1/doc/visualization-brainstorming/monday12-16.md](https://lively-kernel.org/lively4/lively4-bp2019/start.html?load=https://lively-kernel.org/lively4/BP2019RH1/doc/visualization-brainstorming/monday12-16.md)

**Comment by JensLincke** [comment]
css transformations like this don't adjust the bounds of it's elements. Therefore this won't fix since it is not a lively bug, but css html issue
