### ISSUE TITLE
broken link

### ISSUE THREAD

**Issue by DelNono** [LivelyKernel/lively4-core#416]
Broken link on:
[lively4-core](https://github.com/LivelyKernel/lively4-core/tree/gh-pages)/[doc](https://github.com/LivelyKernel/lively4-core/tree/gh-pages/doc)/[tutorial](https://github.com/LivelyKernel/lively4-core/tree/gh-pages/doc/tutorial)
/creating_a_web_component.md

**Comment by onsetsu** [comment]
Thanks for catching the issue.
I merged both links regarding web component in c02ec14.
Hopefully, this provides enough of a starting ground for onboarding new developers.

Please keep us informed about any other issues you find. :)
