### ISSUE TITLE
Ctrl+e is bad for opening expose

### ISSUE THREAD

**Issue by Lixissimus** [LivelyKernel/lively4-core#47]
@TwoLaid Under windows and Ubuntu, `ctrl+e` jumps into the address bar in chrome. Therefore, you can neither toggle the expose without clicking into the body, nor use any other keys to navigate to the desired window. I would suggest to change it to `cmd/ctrl+i`.

**Comment by Lixissimus** [comment]
Oh, `ctrl+i` seems to be blocked by `open inspector`. However, there is no inspector. So could we use it, @JensLincke ?

**Comment by TwoLaid** [comment]
I would imagine that we will have an Inspector at some point, so it would be best to reserve Ctrl+i for now ..

Im not sure what else we could use

**Comment by Lixissimus** [comment]
I thought, the ObjectEditor is also the inspector.

**Comment by j4yk** [comment]
How about Ctrl+^? Or Ctrl+` for US keyboards. The key directly above Tab in
any case, so maybe also consider Alt as the modifier key.

**Comment by Lixissimus** [comment]
ctrl+`/^ is super hard to press, so I wouldn't like that. Also alt+` on Ubuntu switches between windows of the same application. Maybe `alt+q`? That's kinda similar to `alt+tab`.

**Comment by JensLincke** [comment]
can we find somthing else like CTRL+i for now? maybe we will launch the object editor there...

**Comment by j4yk** [comment]
Then maybe look for some Ctrl+Fx binding. Here you might find possibly
"reserved" ones: https://en.wikipedia.org/wiki/Table_of_keyboard_shortcuts
For example, Ctrl+F3, Ctrl+F8 and Ctrl+F9 have no bindings there. According
to that, Ctrl+F6 is "next pane", whatever that means, on Windows.

If you cannot find a free Ctrl+... binding, you might fall back to
Ctrl+Shift+...

I find Alt+Shift+... also quite comfortable to press, at least on my
keyboard.

**Comment by Lixissimus** [comment]
Nice list! According to that list, `alt+q` is still available. I like it, because you can reach it easily from the 10-finger-position. I find it more confortable than reaching blindly for the Fx keys. I have commited it in addition to `cmd+e`, so you can try it out and maybe we can make a decision next wednesday. :)

**Comment by JensLincke** [comment]
I like alt+q... what about alt+w to close our windows?

**Comment by JensLincke** [comment]
or should alt+q maybe toggle then through the windows like alt+tab. maybe in combination with expose?

**Comment by Lixissimus** [comment]
I think, it should toggle through the Windows, yes. I'm not sure, whether the expose should close when the alt key is released (and focus the currently selected window)? How does expose behave on osx?If alt+w is available, it is fine for closing the windows.

-------- Original message --------

**Comment by TwoLaid** [comment]
Expose on os x is pretty much like how I implemented it in lively. press the key -> get overview -> press key again to return or click on window to focus

**Comment by Lixissimus** [comment]
Ok, then we should probably just leave it like this.
