### ISSUE TITLE
Caching too strict on imported modules

### ISSUE THREAD

**Issue by TwoLaid** [LivelyKernel/lively4-core#51]
Developing a module and testing it at the same time is currently very difficult due to caching.

Example:

I am working on the active-expressions module in `/lively4/active-expressions/src/active-expressions.js` and I have a piece of code that tests some of the functionality in `/lively4/active-expressions/tests/playground.js`. The latter imports the module with `import { select } from '../src/active-expressions.js';`

I have both open in the same Tab. Now, when I change anything in the module (`active-expressions.js`) and save it, and then re-eval the `playground.js`, the new changes will not be applied. I need to reload the browser tab to do that, which is not a good workflow.

Browser cache is already disabled via DevTools.

**Comment by JensLincke** [comment]
modules are updated now
