### ISSUE TITLE
Cannot use "/" in commit messages

### ISSUE THREAD

**Issue by TwoLaid** [LivelyKernel/lively4-core#52]
see title.

**Comment by JensLincke** [comment]
the / is stripped out, but the commit does not break

**Comment by JensLincke** [comment]
currently we take the easy road and strip a lot of dangerous content handed to our shell scripts...

![image](https://user-images.githubusercontent.com/1466247/64690407-9c0d3080-d490-11e9-8eee-8319c3948ed4.png)
