### ISSUE TITLE
Import and Handling User-defined Code

### ISSUE THREAD

**Issue by onsetsu** [LivelyKernel/lively4-core#64]
With the core system becoming more and more stable, we need a way for developers to write modules and apps, that are not part of the core system (E.g. the RDFa project is currently tightly coupled to the core system).

Some question that need to be solved:
- How to import user code appropriately, and from where?
  - How should these information be specified?
- How to persist apps with web components and module code?

**Comment by JensLincke** [comment]
external content can load 
a) any url
b) add their components into the search path for templates
