### ISSUE TITLE
Uncommitted Changes Indicator

### ISSUE THREAD

**Issue by onsetsu** [LivelyKernel/lively4-core#68]
Regardless the current or proposed workflow, a small widget indicating whether there are uncommitted changes in the current folder or not might be helpful.
It could even be a small indicator that is always visible, so we can check on start, whether we are on a clean folder.

Additionally, as @fniephaus suggested, when leaving the site, hinting the developer on uncommited changes might also help with the problem.

**Comment by fniephaus** [comment]
@JensLincke and I discussed another suggestion: features are supposed to be developed on feature branches while the main branch and the main [`lively4-core`](https://lively-kernel.org/lively4/lively4-core/) checkout should no longer be used for development. This would also solve the problem of unfinished work getting in the way of developing other features. Nonetheless, a "isDirty" indicator would be very helpful in either way.

**Comment by JensLincke** [comment]
every change is now commited, but some are not synced yet
