### ISSUE TITLE
Windows broken on github.io and localhost (active expressions)

### ISSUE THREAD

**Issue by jgraichen** [LivelyKernel/lively4-core#69]
![20160707cb87fa16](https://cloud.githubusercontent.com/assets/800848/16648728/b5df71e2-4435-11e6-89f7-c891b13470fd.png)
![20160707bdf316a1](https://cloud.githubusercontent.com/assets/800848/16648749/c9f43f64-4435-11e6-8d5b-630756e7298b.png)

Due to active expressions windows *only* work on lively-kernel.org now.

**Comment by TwoLaid** [comment]
This is a problem writing import statements that work on localhost, livelykernel AND github.io .. 
Not sure what the best solution is here

**Comment by jgraichen** [comment]
The best solution is to not break out of the base by either linking or moving it into core or mount it using the service worker (wouldn't work with chrome extension).

**Comment by JensLincke** [comment]
Using subtrees allows us to combine the benefit of local copy with beeing able to update and patch with git... etc. now
