### ISSUE TITLE
Update all module dependents when reloading a single module

### ISSUE THREAD

**Issue by numberpi** [LivelyKernel/lively4-core#71]
I am developing different modules (say A, B and C).
B imports A
C imports A and B

When I change A and save it, I have to reload B and C manually (at the moment by saving them again) to use the new features from A.
Is there a possibility to auto-reload all modules, which use module A, when saving A? On the other hand, is it useful? Because in a workspace I probably do not want this auto reload.

**Comment by j4yk** [comment]
From a continuous integration perspective, it would be useful, if not mandatory. Regarding the workspace, do you mean you would not want all of its code to be reevaluated? If think it would be nice if the imports and prototypes of resident objects would be updated.

**Comment by JensLincke** [comment]
lively.reloadModule takes care of reloading tempending modules...
