### ISSUE TITLE
Support Snapping in Halo Tools

### ISSUE THREAD

**Issue by onsetsu** [LivelyKernel/lively4-core#75]
Currently, when dragging/grapping(can't distinguish these two) and rezising using halos, it is difficult to align multiple elements pixel-perfect. Additionally, moving elements causes their `width`, `height`, `top`, and `bottom` properties to be absolute values.

I think it would be beneficial to let child elements snap to their parents/siblings with some fixed margins to speed up the tool building process.

Does this sound like a feature we want?

**Comment by j4yk** [comment]
I have always liked such snapping features in GUI builders I have used so far. Most GUI frameworks provide stack and table layouting by default. Snapping can help create those layouts if they are not explicitly coded. For that, the snapping should also include automatic alignment (i. e., sticking to edges when the parent is resized), like in [Vivide](/hpi-swa/vivide).

By the way, if you still need topics for upcoming seminars: easy tool building could probably be one, maybe integrating modern approaches to UI design like [Material Design](https://material.google.com/) or others. So at the end, you should be able to create fashionable Lively apps quickly. ;-) A broader topic would be thinking about how Lively could play together with things like AngularJS, Bootstrap etc.

And another by the way: Lively Kernel is listed as "no longer actively developed" on https://en.wikipedia.org/wiki/List_of_JavaScript_libraries#GUI-related_.28widget.29

**Comment by JensLincke** [comment]
implemted
