### ISSUE TITLE
Make git commit author name and e-mail configurable

### ISSUE THREAD

**Issue by j4yk** [LivelyKernel/lively4-core#76]
Git allows you to configure the commit author's name and e-mail address. Using GitHub Sync the name will currently be the GitHub username (not the long, proper name) and the primary GitHub e-mail address.

It might be nice to be able to change that (possibly per repository) because I for one do not like to commit as "j4yk" with my private e-mail address for university projects.

**Comment by JensLincke** [comment]
I think.... sorry... wont fix
