### ISSUE TITLE
Root pointing to the module in the module display.

### ISSUE THREAD

**Issue by nnkps** [LivelyKernel/lively4-core#86]
Example:
If we're viewing https://lively-kernel.org/lively4/lively4-core/start.html?load=https://lively-kernel.org/lively4/lively4-particles/index.html in the lively and we have absolute paths in import, the root of project should be pointed to https://lively-kernel.org/lively4/lively4-particles/ not https://lively-kernel.org/lively4/lively4-core/

**Comment by JensLincke** [comment]
should work now
