### ISSUE TITLE
Support template loading from non-core repositories

### ISSUE THREAD

**Issue by davidrauch** [LivelyKernel/lively4-core#89]
For example, loading a template from the repository "lively4-projectional-editor" currently requires the following workaround:
```
// Fake the Lively URL to load the template from our own folder
let oldLively4Url = lively4url;
lively4url = location.origin + '/lively4/lively4-projectional-editor';
lively.registerTemplate()

// Reset the Lively URL to the original
lively4url = oldLively4Url;
```
(see [this file](https://lively-kernel.org/lively4/lively4-core/start.html?edit=https://lively-kernel.org/lively4/lively4-projectional-editor/templates/lively-projectional-editor.html))

This could be automated, for example by looking for the .js file in the same folder as the .html file from which `lively.registerTemplate()` is called.

**Comment by JensLincke** [comment]
implemented template search path
